index:
    path: /
    controller: App\Controller\HomeController::index
request:
    path: /request
    controller: App\Controller\HomeController::request
    methods:  [POST]
rate:
    path: /rate
    controller: App\Controller\HomeController::rate
    methods:  [POST]